# Generated by Django 5.2.5 on 2025-09-12 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_am', models.TextField()),
                ('name_en', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='departments.departments')),
                ('teams', models.ManyToManyField(blank=True, related_name='services', to='teams.teams')),
                ('users', models.ManyToManyField(related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
