# Generated by Django 5.2.5 on 2025-09-13 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'services'},
        ),
        migrations.AlterModelTable(
            name='services',
            table='services',
        ),
    ]
