# Generated by Django 5.2.5 on 2025-09-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('user', 'user'), ('pending', 'pending')], default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender_am',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession_am',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
