# Generated by Django 5.2.5 on 2025-09-12 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('subServices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='subService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='subServices.subservices'),
        ),
    ]
