# Generated by Django 5.2.5 on 2025-09-16 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_alter_services_options_alter_services_table'),
        ('subServices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('additional', 'Additional')], max_length=20)),
                ('service_snapshot', models.JSONField(blank=True, null=True)),
                ('sub_service_snapshot', models.JSONField(blank=True, null=True)),
                ('name_am', models.TextField()),
                ('name_en', models.TextField()),
                ('quality', models.CharField(blank=True, max_length=10, null=True)),
                ('frequency', models.CharField(max_length=10)),
                ('starting_time', models.CharField(max_length=10)),
                ('ending_time', models.CharField(max_length=10)),
                ('total_hour', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=20)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='services.services')),
                ('sub_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='subServices.subservices')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
            },
        ),
    ]
