# Generated by Django 5.2.5 on 2025-09-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='activity_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
