# Generated by Django 5.2.5 on 2025-09-12 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_am', models.TextField()),
                ('name_en', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subServices', to='services.services')),
            ],
            options={
                'verbose_name': 'SubService',
                'verbose_name_plural': 'subServices',
                'db_table': 'subServices',
            },
        ),
    ]
